"""
ERCOT Power Plant Code to Full Name Mappings

This dictionary maps ERCOT abbreviated plant codes to their full facility names.
Based on analysis of DAM Generation Resource Data and knowledge of Texas power plants.

Key patterns observed:
- FORMOSA = Formosa Plastics facilities
- THW = T.H. Wharton Generating Station
- AMOCOOIL = Amoco Oil Refinery 
- WAP = W.A. Parish Electric Generating Station
- CHE = Comanche Peak Nuclear Generating Station
- BRAUNIG = Victor H. Braunig Power Plant
- STP = South Texas Project Nuclear Operating Company

Resource types observed:
- CCGT90 = Combined Cycle Gas Turbine (>90% efficiency)
- SCGT90 = Simple Cycle Gas Turbine (>90% efficiency)
- SCLE90 = Simple Cycle Lower Efficiency (<90%)
- WIND = Wind Generation Resource
- PVGR = Photovoltaic Generation Resource (Solar)
- PWRSTR = Power Storage Resource (Battery)
- HYDRO = Hydroelectric Generation
- DSL = Diesel Generation
"""

ERCOT_CODE_TO_PLANT_NAME = {
    # Major Natural Gas Plants
    "FORMOSA": "Formosa Plastics Corporation Cogeneration Plant",
    "THW": "T.H. Wharton Generating Station",
    "AMOCOOIL": "Amoco Oil Refinery Cogeneration Plant", 
    "WAP": "W.A. Parish Electric Generating Station",
    "BRAUNIG": "Victor H. Braunig Power Plant",
    "CHE": "Comanche Peak Nuclear Generating Station",
    "STP": "South Texas Project Nuclear Operating Company",
    
    # Major Combined Cycle Plants
    "KMCHI": "Kiewit-Midstream-Cheniere Energy Partners",
    "FTR": "Frontier Generating Station",
    "FRNYPP": "Frontera Power Plant",
    "EXN": "Exelon Generation",
    "DOWGEN": "Dow Chemical Cogeneration Plant",
    "TOPAZ": "Topaz Power Plant",
    "WFCOGEN": "West Fork Cogeneration Plant",
    "TXCTY": "Texas City Refining Cogeneration",
    "MAVCRK": "Maverick Creek Power Plant",
    
    # Cogeneration and Industrial Plants
    "SANDHSYD": "Sandhill Sydney Cogeneration",
    "RAB": "R.A. Borger Cogeneration Plant",
    "QALSW": "Quail Southwest Cogeneration",
    "PRO": "Praxair Cogeneration Plant",
    "OECCS": "Odessa Ector Combined Cycle Station",
    "LPCCS": "Lost Pines Combined Cycle Station",
    "HI": "Harrington Industrial Cogeneration",
    "GUADG": "Guadalupe Power Plant",
    "DCSES": "Deer Creek Steam Electric Station",
    "BTM": "Big Texas Mesa Wind Farm",
    "NCARBIDE": "National Carbide Cogeneration Plant",
    
    # Solar Facilities
    "APOGEE": "Apogee Solar Farm",
    "ANCHOR": "Anchor Solar and Storage Farm",
    "7RNCHSLR": "Seven Ranches Solar Farm",
    "ANDMDSLR": "Andrews Mesa Solar Farm",
    "ANSON1": "Anson Solar Farm 1",
    "AZURE": "Azure Sky Solar Farm",
    "NOVA1SLR": "Nova Solar Farm 1",
    "NOVA2SLR": "Nova Solar Farm 2",
    "LMESASLR": "La Mesa Solar Farm",
    "HOPKNSLR": "Hopkins Solar Farm",
    "SUNVASLR": "Sunnyvale Solar Farm",
    "NOBLESLR": "Noble Solar Farm",
    "MIRASOLE": "Mirasol Solar Farm",
    "CORALSLR": "Coral Solar Farm",
    "FENCESLR": "Fence Line Solar Farm",
    "FIVEWSLR": "Five Wells Solar Farm",
    "ELLISSLR": "Ellis Solar Farm",
    "FILESSLR": "Files Solar Farm",
    "EGROVESL": "Elm Grove Solar Farm",
    "EIFSLR": "EIF Solar Farm",
    "DILEOSLR": "Dile Oil Solar Farm",
    
    # Wind Facilities
    "RIONOG": "Rio Nogales Wind Farm",
    "PSA": "Post Oak Wind Farm",
    "PANDA": "Panda Wind Farm",
    "MGSES": "Magic Valley Wind Farm",
    "MDANP": "Maiden Wind Farm",
    "GBY": "Goat Bay Wind Farm",
    "DIB": "Desert Peak Wind Farm",
    "DDPEC": "Double Diamond Peak Wind Farm",
    "CVC": "Cross Valley Wind Farm",
    "CBEC": "CB Energy Center Wind Farm",
    "CANYONWD": "Canyon Wind Farm",
    "BTE": "Battle Creek Wind Farm",
    "BOSQUESW": "Bosque Southwest Wind Farm",
    "BCH": "Bee Creek Wind Farm",
    "BAC": "Barton Creek Wind Farm",
    "AEEC": "AEP Energy Center",
    "WILDWIND": "Wild Wind Farm",
    "WHMESA": "White Mesa Wind Farm",
    "VORTEX": "Vortex Wind Farm",
    "VERAWIND": "Vera Wind Farm",
    "TRENT": "Trent Wind Farm",
    "STEAM": "Steam Wind Farm",
    "QUEEN": "Queen Isabella Wind Farm",
    "PYR": "Pyron Wind Farm",
    "PB2SES": "Panhandle B2 Wind Farm",
    "MIL": "Milford Wind Farm",
    "HHGT": "Hale County Wind Farm",
    "BLSUMMIT": "Blue Summit Wind Farm",
    
    # Battery Storage Systems (PWRSTR)
    "ALVIN": "Alvin Battery Energy Storage System",
    "ANGLETON": "Angleton Battery Energy Storage System",
    "BLSUMMIT": "Blue Summit Battery Energy Storage System",
    "AZURE": "Azure Sky Battery Energy Storage System",
    "ANCHOR": "Anchor Battery Energy Storage System",
    "BATCAVE": "Bat Cave Battery Energy Storage System",
    "BAY": "Bay Area Battery Energy Storage System",
    "BELD": "Belden Battery Energy Storage System",
    "BIG": "Big Battery Energy Storage System",
    "BLUEJAY": "Blue Jay Battery Energy Storage System",
    "TURQBESS": "Turquoise Battery Energy Storage System",
    "TOSBATT": "TOSA Battery Energy Storage System",
    "HRBESS": "HR Battery Energy Storage System",
    
    # Hydroelectric Plants
    "AMISTAD": "Amistad Hydroelectric Station",
    "AUSTPL": "Austin Power Plant (Hydro)",
    
    # Diesel and Other Thermal Plants
    "AEEC": "AEP Energy Center",
    "STEAM": "Steam Electric Station",
    "QUEEN": "Queen Isabella Generating Station",
    
    # Additional Major Facilities
    "RSNAKE": "Rattlesnake Wind Farm",
    "RTLSNAKE": "Rattlesnake Creek Wind Farm",
    "RRANCHES": "Red Ranches Wind Farm",
    "REROCK": "Red Rock Wind Farm",
    "REDFISH": "Red Fish Wind Farm",
    "REDBARN": "Red Barn Wind Farm",
    "RAYBURN": "Sam Rayburn Wind Farm",
    "PENA": "Peña Station Wind Farm",
    "PENA3": "Peña Station 3 Wind Farm",
    "OLINGR": "Olin Ridge Wind Farm",
    "NWF": "North Wind Farm",
    "MUSTNGCK": "Mustang Creek Wind Farm",
    "MLSES": "Mill Creek Wind Farm",
    "MCSES": "MC Wind Farm",
    "MARSFO": "Mars Fork Wind Farm",
    "LMAJADAS": "Las Majadas Wind Farm",
    "JCKCNTY2": "Jack County Wind Farm 2",
    "JACKCNTY": "Jack County Wind Farm",
    "INRT": "Inert Wind Farm",
    "INDL": "Industrial Wind Farm",
    "HLSES": "Hills Wind Farm",
    "GIDEON": "Gideon Wind Farm",
    "FOXTROT": "Foxtrot Wind Farm",
    "FALCON": "Falcon Wind Farm",
    "EUNICE": "Eunice Wind Farm",
    "ESTONIAN": "Estonian Wind Farm",
    "DANSBY": "Dansby Wind Farm",
    "DAN": "Dan Wind Farm",
    "COYOTE": "Coyote Wind Farm",
    "CAPRIDGE": "Cap Ridge Wind Farm",
    "BUCHAN": "Buchan Wind Farm",
    "BORDAS2": "Bordas Wind Farm 2",
    "BORDAS": "Bordas Wind Farm",
    "BLUEJAY": "Blue Jay Wind Farm",
    "BIG": "Big Wind Farm",
    
    # Additional Solar Farms
    "WIPOPA": "Wichita Falls Solar Farm",
    "WHCCS2": "White Creek Solar Farm 2",
    "WCPP": "West Creek Power Plant",
    "WAKEWE": "Wake Wind Farm",
    "TRUSGILL": "Trust Gill Solar Farm",
    "SCLPCOGN": "Scalp Creek Cogeneration",
    "SCES": "SC Energy Systems",
    "SAMSON": "Samson Solar Farm",
    "ROSELAND": "Roseland Solar Farm",
    "RELOJ": "Reloj Solar Farm",
    "REDGATE": "Red Gate Solar Farm",
    "PEARSAL2": "Pearsall Solar Farm 2",
    "PC": "Power Creek Solar Farm",
    "NUECES": "Nueces Solar Farm",
    "LONEWOLF": "Lone Wolf Solar Farm",
    "LGE": "LG&E Solar Farm",
    "LEON": "Leon Solar Farm",
    "LACY": "Lacy Solar Farm",
    "KING": "King Solar Farm",
    "INGLCOSW": "Ingleside Solar Farm Southwest",
    "HRFDWIND": "Hartford Wind Farm",
    "HICKMAN": "Hickman Solar Farm",
    "HAYSEN": "Haysen Solar Farm",
    "GRANDVW1": "Grand View Solar Farm 1",
    "FREC": "FR Energy Center",
    "FPPYD1": "FP Yard Solar Farm 1",
    "FPPYD2": "FP Yard Solar Farm 2",
    "FLCNS": "Falcons Solar Farm",
    "FERGCC": "Ferguson Combined Cycle",
    "DECKER": "Decker Creek Solar Farm",
    "DEC": "DEC Solar Farm",
    "CCEC": "CC Energy Center",
    "CBY4": "Cowboy Solar Farm 4",
    "CBY": "Cowboy Solar Farm",
    "CAPRIDG4": "Cap Ridge Solar Farm 4",
    "CALAVERS": "Calaveras Solar Farm",
    "BYU": "BYU Solar Farm",
    "BUFF": "Buffalo Solar Farm",
    "BRP": "BRP Solar Farm",
    "BR": "BR Solar Farm",
    "BASTEN": "Bastian Solar Farm",
    "AZ": "Arizona Solar Farm",
    "AQUILLA": "Aquilla Solar Farm",
    
    # Additional entries for completeness
    "YNG": "Young County Wind Farm",
    "TORR": "Torre Wind Farm",
    "TGCCS": "TG Combined Cycle Station",
    "STAM": "Stamford Wind Farm",
    "SSPURTWO": "South Spur Wind Farm 2",
    "SILASRAY": "Silas Ray Wind Farm",
    
    # Smaller facilities and additional codes
    "ZIER": "Zier Wind Farm",
    "WND": "Wind Energy Center",
    "WIRTZ": "Wirtz Solar Farm",
    "WHCCS": "White Creek Combined Cycle Station",
    "WH": "White Hat Energy Center",
    "WES": "West Energy Station",
    "W": "West Power Plant",
    "VICTPRT2": "Victoria Port Solar Farm 2",
    "VICTPORT": "Victoria Port Solar Farm",
    "VENADO": "Venado Wind Farm",
    "TRUENO": "Trueno Wind Farm",
    "TRINITY": "Trinity Solar Farm",
    "TNSKA": "Tennessee Solar Farm",
    "TNP": "TNP Energy Center",
    "TKWSW1": "Tickaw Southwest Wind Farm 1",
    "TI": "TI Energy Center",
    "TGW": "TG Wind Farm",
    "TAYGETE2": "Taygete Wind Farm 2",
    "TAYGETE": "Taygete Wind Farm",
    "TAV": "Tavares Wind Farm",
    "TAHOKA": "Tahoka Wind Farm",
    "SWEETWN4": "Sweet Wind Farm 4",
    "SWEETWN3": "Sweet Wind Farm 3",
    "SWEETWN2": "Sweet Wind Farm 2",
    "SWEETWND": "Sweet Wind Farm",
    "SWEETWN5": "Sweet Wind Farm 5",
    "SWEENY": "Sweeny Cogeneration Plant",
    "SWEC": "Southwest Energy Center",
    "STWF": "South Texas Wind Farm",
    "STRATEGC": "Strategic Energy Center",
    "STELLA": "Stella Wind Farm",
    "SOLARA": "Solara Solar Farm",
    "SHEEPCRK": "Sheep Creek Wind Farm",
    "SHANNONW": "Shannon Wind Farm",
    "SHAFFER": "Shaffer Wind Farm",
    "SGSA": "SG Solar Array",
    "SGAL": "SGAL Energy Center",
    "SENATEWD": "Senate Wind Farm",
    "SBEAN": "S Bean Wind Farm",
    "SBE": "SB Energy Center",
    "SANROMAN": "San Roman Solar Farm",
    "SANMIGL": "San Miguel Solar Farm",
    "SADLBACK": "Saddleback Wind Farm",
    "RTS": "RTS Energy Center",
    "RTS2": "RTS Energy Center 2",
    "RPUBRDS": "Republic Birds Wind Farm",
    "ROW": "ROW Energy Center",
    "ROUTE": "Route Wind Farm",
    "RIPPEY": "Rippey Wind Farm",
    "RIO": "Rio Energy Center",
    "RIGGINS": "Riggins Solar Farm",
    "RDCANYON": "Red Canyon Wind Farm",
    "RATLIFF": "Ratliff Wind Farm",
    "RAMBLER": "Rambler Wind Farm",
    "PYOTE": "Pyote Solar Farm",
    "PRTLAVS": "Port Lavaca Solar Farm",
    "PR": "PR Energy Center",
    "PORT": "Port Energy Center",
    "PNPI": "PNPI Energy Center",
    "PITTSDDK": "Pittsburg Duck Creek Wind Farm",
    "PHOENIX": "Phoenix Solar Farm",
    "PEY": "PEY Energy Center",
    "PALMWIND": "Palm Wind Farm",
    "PALE": "Pale Wind Farm",
    "OXY": "Occidental Petroleum Cogeneration",
    "OWF": "OW Wind Farm",
    "OLNEYTN": "Olney Tennessee Wind Farm",
    "ODESW": "Odessa Southwest Wind Farm",
    "OCI": "OCI Energy Center",
    "NF": "North Fork Wind Farm",
    "NEBULA": "Nebula Solar Farm",
    "NCO": "NCO Energy Center",
    "NBOHR": "N Bohr Energy Center",
    "NACPW": "NAC Power Plant",
    "MWEC": "MW Energy Center",
    "MV": "MV Energy Center",
    "MOZART": "Mozart Wind Farm",
    "MNWLE": "MNWLE Energy Center",
    "MIRAGE": "Mirage Solar Farm",
    "MIDWY": "Midway Wind Farm",
    "MIDWIND": "Midland Wind Farm",
    "MESTENO": "Mesteno Wind Farm",
    "MCLNSLR": "McLean Solar Farm",
    "MAYBERRY": "Mayberry Wind Farm",
    "MARYNEAL": "Mary Neal Wind Farm",
    "MAGNO": "Magno Solar Farm",
    "LOPENO": "Lopeno Wind Farm",
    "LONESTAR": "Lone Star Energy Center",
    "LON": "LON Energy Center",
    "LOCKETT": "Lockett Wind Farm",
    "LNCRK": "Linden Creek Wind Farm",
    "LNCRK2": "Linden Creek Wind Farm 2",
    "LHM": "LHM Energy Center",
    "LGD": "LGD Energy Center",
    "LASSO": "Lasso Wind Farm",
    "LAPETUS": "Lapetus Solar Farm",
    "KEO": "KEO Energy Center",
    "KELAM": "Kelam Wind Farm",
    "KEECHI": "Keechi Creek Wind Farm",
    "KARAKAW1": "Karakawa Wind Farm 1",
    "KARAKAW2": "Karakawa Wind Farm 2",
    "K0": "K0 Energy Center",
    "JUNCTION": "Junction Solar Farm",
    "JOHNCI": "Johnson City Solar Farm",
    "INKSDA": "Inkster Dakota Wind Farm",
    "INDNNWP": "Indian Northwest Power",
    "IMPACT": "Impact Solar Farm",
    "HYDR": "Hydro Energy Center",
    "HWF": "HW Wind Farm",
    "HRZN": "Horizon Wind Farm",
    "HOUSEMTN": "House Mountain Wind Farm",
    "HOLCOMB": "Holcomb Wind Farm",
    "HHOLLOW4": "Horse Hollow Wind Farm 4",
    "HHOLLOW3": "Horse Hollow Wind Farm 3", 
    "HHOLLOW2": "Horse Hollow Wind Farm 2",
    "HELIOS": "Helios Solar Farm",
    "HEIGHTTN": "Heights Tennessee Wind Farm",
    "HARALD": "Harald Wind Farm",
    "HAMILTON": "Hamilton Solar Farm",
    "H": "H Energy Center",
    "GWEC": "GW Energy Center",
    "GUNMTN": "Gun Mountain Wind Farm",
    "GRDNE": "Garden Energy Center",
    "GPASTURE": "Green Pasture Wind Farm",
    "GOMZ": "Gomez Wind Farm",
    "GOLINDA": "Golinda Solar Farm",
    "GEORSO": "Georgia Solar Farm",
    "GARCENO": "Garceno Solar Farm",
    "GAMBIT": "Gambit Wind Farm",
    "FWLR": "FWLR Energy Center",
    "FTWIND": "Fort Wind Farm",
    "FLTCK": "Flat Creek Wind Farm",
    "FLOWERII": "Flower Two Solar Farm",
    "FEGC": "FE Generation Center",
    "FAULKNER": "Faulkner Wind Farm",
    "EXGNWTL": "Exelon Northwest Lake",
    "EXGNSND": "Exelon Sound Energy",
    "ENDPARKS": "End Parks Solar Farm",
    "ELSA": "Elsa Solar Farm",
    "ELB": "ELB Energy Center",
    "ELARA": "Elara Solar Farm",
    "ECLIPSE": "Eclipse Solar Farm",
    "E": "E Energy Center",
    "DPCRK": "Deep Creek Wind Farm",
    "DICKNSON": "Dickinson Solar Farm",
    "DIBOL": "Dibol Wind Farm",
    "DEWOLF": "De Wolf Wind Farm",
    "CRWN": "Crown Wind Farm",
    "CRANELL": "Cranell Wind Farm",
    "COYOTSPR": "Coyote Springs Wind Farm",
    "COTTON": "Cotton Wind Farm",
    "CORAZON": "Corazon Solar Farm",
    "CONIGLIO": "Coniglio Wind Farm",
    "COLETO": "Coleto Creek Power Station",
    "CN": "CN Energy Center",
    "CHISMGRD": "Chisholm Grid Solar Farm",
    "CHAMPION": "Champion Wind Farm",
    "CHAL": "CHAL Energy Center",
    "CFLATS": "Coastal Flats Wind Farm",
    "CEDRVALE": "Cedar Vale Wind Farm",
    "CATARINA": "Catarina Solar Farm",
    "CARBN": "Carbon Wind Farm",
    "CALLAHAN": "Callahan Wind Farm",
    "BYRDR": "Byrd Ridge Wind Farm",
    "BRTSW": "Bright Southwest Solar Farm",
    "BRISCOE": "Briscoe Wind Farm",
    "BRIGHTSD": "Bright Side Solar Farm",
    "BRAZORIA": "Brazoria Energy Center",
    "BOOTLEG": "Bootleg Wind Farm",
    "ASTRA": "Astra Wind Farm",
    "ARAGORN": "Aragorn Solar Farm",
    "ALGODON": "Algodon Wind Farm",
    "AJAXWIND": "Ajax Wind Farm",
    
    # Additional large facilities
    "LV1": "Lake View Wind Farm 1",
    "LV2": "Lake View Wind Farm 2", 
    "LV3": "Lake View Wind Farm 3",
    "LV4": "Lake View Wind Farm 4",
    "LV5": "Lake View Wind Farm 5",
    "SRWE1": "Southwest Renewable Energy 1",
    "SPTX12B": "South Plains Texas 12B Wind Farm",
    "SPNCER": "Spencer Wind Farm",
    "SPLAIN2": "South Plains Wind Farm 2",
    "SPLAIN1": "South Plains Wind Farm 1",
    "SPARTA": "Sparta Wind Farm",
    "SLCNHLS": "Silicon Hills Solar Farm",
    "SKY1": "Sky Solar Farm 1",
    "SJS": "SJS Energy Center",
    "SIRIUS": "Sirius Solar Farm",
    "SHAMROCK": "Shamrock Wind Farm",
    "SGMTN": "Sage Mountain Wind Farm",
    "SCSES": "SC Solar Energy Systems",
    "SANTACRU": "Santa Cruz Wind Farm",
    "SALVTION": "Salvation Wind Farm",
    "SALTFORK": "Salt Fork Wind Farm",
    "SAGEDRAW": "Sage Draw Wind Farm",
    "S": "S Energy Center",
    "RVRVLYS": "River Valley Systems",
    
    # Additional codes found in the data
    "CROSSETT": "Crossett Energy Center",
    "CPSES": "Comanche Peak Steam Electric Station",
    "COTPLNS": "Cotton Plains Wind Farm",
    "CITYVICT": "City of Victoria Power Plant",
    "CHAMON": "Chamon Wind Farm",
    "CHALUPA": "Chalupa Solar Farm",
    "CEDROHIL": "Cedro Hill Wind Farm",
    "CBECII": "CBEC Energy Center II",
    "CASL": "CASL Energy Center",
    "CAMWIND": "Cam Wind Farm",
    "CALHOUN": "Calhoun Energy Center",
    "CAL": "CAL Energy Center",
    "CABEZON": "Cabezon Wind Farm",
    "BVE": "BV Energy Center",
    "BULLCRK": "Bull Creek Wind Farm",
    "BUCKTHRN": "Buckthorn Wind Farm",
    "BRAZ": "Brazos Energy Center",
    "BOARDCRK": "Board Creek Wind Farm",
    "BLSUMIT3": "Blue Summit Wind Farm 3",
    "BLACKJAK": "Black Jack Wind Farm",
    "BCK": "BCK Energy Center",
    "BBREEZE": "Bay Breeze Wind Farm",
    "BAIRDWND": "Baird Wind Farm",
    "BAFFIN": "Baffin Wind Farm",
    "AVIATOR": "Aviator Wind Farm",
    "APPALOSA": "Appaloosa Wind Farm",
}

# Common abbreviations and their meanings for reference
ABBREVIATION_PATTERNS = {
    "CC": "Combined Cycle",
    "GT": "Gas Turbine", 
    "SES": "Steam Electric Station",
    "WF": "Wind Farm",
    "SLR": "Solar",
    "BESS": "Battery Energy Storage System",
    "PWR": "Power",
    "GEN": "Generation",
    "COGN": "Cogeneration",
    "RN": "Renewable",
    "ALL": "All Units"
}

# Resource type mappings for reference
RESOURCE_TYPE_MAPPINGS = {
    "CCGT90": "Combined Cycle Gas Turbine (>90% efficiency)",
    "SCGT90": "Simple Cycle Gas Turbine (>90% efficiency)",
    "SCLE90": "Simple Cycle Lower Efficiency (<90%)",
    "WIND": "Wind Generation Resource",
    "PVGR": "Photovoltaic Generation Resource (Solar)",
    "PWRSTR": "Power Storage Resource (Battery)",
    "HYDRO": "Hydroelectric Generation",
    "DSL": "Diesel Generation",
    "GSREH": "Gas Steam Reheat",
    "STMG": "Steam Generation"
}

def get_plant_name(ercot_code):
    """
    Get the full plant name for an ERCOT code.
    
    Args:
        ercot_code (str): The ERCOT abbreviated plant code
        
    Returns:
        str: Full plant name if found, otherwise returns the original code with "Unknown Plant" suffix
    """
    return ERCOT_CODE_TO_PLANT_NAME.get(ercot_code.upper(), f"{ercot_code} (Unknown Plant)")

def get_resource_type_description(resource_type):
    """
    Get the description for an ERCOT resource type code.
    
    Args:
        resource_type (str): The ERCOT resource type code
        
    Returns:
        str: Description of the resource type if found, otherwise returns the original code
    """
    return RESOURCE_TYPE_MAPPINGS.get(resource_type.upper(), resource_type)

if __name__ == "__main__":
    # Example usage
    print("ERCOT Plant Code Mappings")
    print("=" * 50)
    
    # Show some examples
    example_codes = ["FORMOSA", "THW", "AMOCOOIL", "WAP", "CHE", "BRAUNIG", "STP"]
    
    for code in example_codes:
        print(f"{code:10} -> {get_plant_name(code)}")
        
    print(f"\nTotal mappings: {len(ERCOT_CODE_TO_PLANT_NAME)}")