[build]
# Use all available cores for compilation
jobs = 24                      # Use all 24 cores for parallel compilation

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native",         # Optimize for your specific CPU
    "-C", "codegen-units=256",         # Maximum parallel codegen units  
    "-C", "opt-level=3",               # Maximum optimization
    "-C", "debuginfo=0",               # No debug info for faster builds
    "-C", "incremental=true",          # Enable incremental compilation
]

[profile.release]
opt-level = 3              # Maximum optimization
lto = false               # Disable LTO for faster compilation (re-enable for final builds)
codegen-units = 256       # Maximum parallelism during compilation
panic = "abort"           # Smaller binary, faster compilation
strip = true              # Strip symbols for smaller binary
debug = false             # No debug info
incremental = true        # Enable incremental compilation

[profile.dev]
opt-level = 0             # No optimization for faster dev builds
debug = true              # Keep debug info for dev
codegen-units = 256       # Still use parallel compilation
incremental = true        # Incremental compilation for faster rebuilds

[profile.dev.package."*"]
opt-level = 2             # Optimize dependencies even in dev mode

[env]
CARGO_BUILD_JOBS = "24"   # Force cargo to use 24 parallel jobs
RUSTFLAGS = "-C codegen-units=256"